### PR TITLE
Rename build.log to _hashdist/build.log

### PR DESCRIPTION
**Pull request by johannesring**
This fixes issue [#441](https://github.com/hashdist/hashstack/issues/441) in hashstack.

### CODE REVIEW

**Comment by cekees** [comment]
Thanks a lot. +1 to merge this.

**Comment by certik** [comment]
+1 if tests pass.

**Comment by johannesring** [comment]
I have fixed the failing test. Please take a look and see if you agree.

**Comment by cekees** [comment]
That looks good to me. I suppose we could put all of those generated files in _hashdist/ to prevent any future trouble.  Or  prefix them all with hashdist_ and get rid  of the _hashdist subdir.

**Comment by johannesring** [comment]
I agree that it would be good to do something about all those generated files, but we can do that in another PR. I will merge this now.

**Pull request merged**
