### PR TITLE
WIP: adding hg support

### PR DESCRIPTION
**Pull request by davclark**
This is not actually a pull request yet, but @ahmadia said it would be useful to show some of my work so far if folks want to comment. I'll keep working in the meantime.

Unfortunately, it's kind of hard to see what I've changed so far from the copy of GitSourceCache -> HgSourceCache. But it should be pretty obvious what's still git and what's hg.

### CODE REVIEW

**Comment by jcftang** [comment]
@ahmadia any update on this?

**Comment by ahmadia** [comment]
It's on my guilt list!

**Comment by jcftang** [comment]
I think once this is merged (whenever) bzr would be next on the list of things to add. Hence the interest in seeing where this is going to head.

**Comment by davclark** [comment]
I'm somewhat responsible for this stagnating also... I currently don't have the bandwidth to do much with this, and anyone else is welcome to hijack it / kill it.

**Comment by jcftang** [comment]
I might take a look at writing some tests for this or at least rebase the series of commits.

**Comment by davclark** [comment]
Seems unlikely to be up-to-date / mergable at all anymore!

**Pull request closed without merging**
